version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: opotest-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: opotest
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
